# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74d64ff60d6c4fb2597c17f8f7f9dd161fc9c308115dc01acdb663cfb88c2ed54faf0113c5d112f0f1ab154f7053eb667dc41fc394198b2d6fad5e2fba8c6b8c

test:
  secret_key_base: c5eefea189addac18401b9c3d1515c813b85dfd2bc651d8b2098edf67144efadf512915a3a9b2db4bbf1ff3e2f52b7e0b255809ba6116c2e4816fc8d5e9dcf07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
